//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_login_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_materiel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detail_materiel()
        {
            this.histoir = new HashSet<histoir>();
            this.materiel = new HashSet<materiel>();
        }
    
        public int id_materiel { get; set; }
        public Nullable<int> id_type_materiel { get; set; }
        public string fiche_technique { get; set; }
        public string etat { get; set; }
        public Nullable<System.DateTime> date_entr { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual type_materiel type_materiel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<histoir> histoir { get; set; }
        public virtual materiel_difectue materiel_difectue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materiel> materiel { get; set; }
    }
}
