//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_login_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SERVICES_RESSOURCES_FINANCIERESEntities1 : DbContext
    {
        public SERVICES_RESSOURCES_FINANCIERESEntities1()
            : base("name=SERVICES_RESSOURCES_FINANCIERESEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bureau> bureau { get; set; }
        public virtual DbSet<detail_materiel> detail_materiel { get; set; }
        public virtual DbSet<histoir> histoir { get; set; }
        public virtual DbSet<materiel> materiel { get; set; }
        public virtual DbSet<materiel_difectue> materiel_difectue { get; set; }
        public virtual DbSet<type_materiel> type_materiel { get; set; }
        public virtual DbSet<type_service> type_service { get; set; }
    }
}
